// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuXuU3BDeJXOSPPbXLSFoNtfINnubPeFk',
    appId: '1:742682476509:web:df523f635e7a5aa0804034',
    messagingSenderId: '742682476509',
    projectId: 'studying-firebase-3ef1f',
    authDomain: 'studying-firebase-3ef1f.firebaseapp.com',
    storageBucket: 'studying-firebase-3ef1f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB_ag9Uy2xpAjvJtV6yNP6aKrWml5ADxI',
    appId: '1:742682476509:android:715c501a8c2f9564804034',
    messagingSenderId: '742682476509',
    projectId: 'studying-firebase-3ef1f',
    storageBucket: 'studying-firebase-3ef1f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2RSBlpHaVC2AAUqIodrPmtsX1Yfh66Qg',
    appId: '1:742682476509:ios:d74a3e9492dab823804034',
    messagingSenderId: '742682476509',
    projectId: 'studying-firebase-3ef1f',
    storageBucket: 'studying-firebase-3ef1f.appspot.com',
    iosBundleId: 'com.studyingfirebase.studyingfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2RSBlpHaVC2AAUqIodrPmtsX1Yfh66Qg',
    appId: '1:742682476509:ios:18c6404315f2e9ab804034',
    messagingSenderId: '742682476509',
    projectId: 'studying-firebase-3ef1f',
    storageBucket: 'studying-firebase-3ef1f.appspot.com',
    iosBundleId: 'com.studyingfirebase.studyingfirebase.RunnerTests',
  );
}
